name: Monthly Job

on:
  schedule:
    - cron: '0 1 1 * *'  # 每月1号的UTC时间1:00，相当于中国标准时间上午9:00
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Tesseract OCR
      run: sudo apt-get install -y tesseract-ocr

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run notify script
      env:
        APP_TOKEN: ${{ secrets.APP_TOKEN }}  # 从Secrets中读取AppToken
        UIDS: ${{ secrets.UIDS }}  # 从Secrets中读取UID列表
      run: python notify.py
